language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
  - nightly

git:
  depth: 1

notifications:
  email:
    - mail-github@sh-dev.de

install:
  - composer install

script:
  - vendor/bin/phpunit --no-coverage tests/Shdev/FlashText/KeywordProcessor/
  - php tests/Shdev/FlashText/flashtext_vs_regex.php